// src/components/ui/progress.tsx
"use client"

import * as ProgressPrimitive from "@radix-ui/react-progress"
import * as React from "react"

import { cn } from "@/lib/utils"

const Progress = React.forwardRef<
  React.ElementRef<typeof ProgressPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof ProgressPrimitive.Root>
>(({ className, value, ...props }, ref) => (
  <ProgressPrimitive.Root
    ref={ref}
    className={cn(
      "relative h-2 w-full overflow-hidden rounded-full bg-white",
      className
    )}
    {...props}
  >
    <ProgressPrimitive.Indicator
      className="h-full w-full flex-1 bg-blue-600 transition-all dark:bg-blue-600"
      style={{ transform: `translateX(-${100 - (value ?? 0)}%)` }}
    />
  </ProgressPrimitive.Root>
))
Progress.displayName = ProgressPrimitive.Root.displayName

export { Progress }

// src/lib/components/ui/progress/progress.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js";
	import { Progress as ProgressPrimitive } from "bits-ui";

	type $$Props = ProgressPrimitive.Props;

	let className: $$Props["class"] = undefined;
	export let value: $$Props["value"] = undefined;
	export { className as class };
</script>

<ProgressPrimitive.Root
	class={cn("relative h-2 w-full overflow-hidden rounded-full bg-white", className)}
	{...$$restProps}
>
	<div
		class="h-full w-full flex-1 bg-blue-600 transition-all dark:bg-blue-600"
		style={`transform: translateX(-${100 - (value ?? 0)}%)`}
	></div>
</ProgressPrimitive.Root>
