// src/routes/dashboard/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import PageDashboardProjects from '$lib/components/PageDashboardProjects.svelte';
	import PageProgressBar from '$lib/components/PageProgressBar.svelte';
	import { Button } from '$lib/components/ui/button';
	import { DASHBOARD_VIEWS } from '$lib/constants';
	import { dashboardStore } from '$lib/stores/dashboardStore.svelte';
	import { timer } from '$lib/stores/timerStore.svelte';

	const { data } = $props();
	const { userProfile } = $derived(data);

	$effect(() => {
		if (!userProfile || !userProfile.id) {
			goto('/auth/login');
		}
	});
</script>

{#if timer.isNotFinished}
	<PageProgressBar />
{/if}

{#if timer.isFinished}
	<div class="flex h-full w-full gap-8">
		<div class="w-[20%] min-w-[250px]">
			<Button
				variant="ghost"
				class="text-white"
				onclick={() => (dashboardStore.currentView = DASHBOARD_VIEWS.PROJECTS)}
			>
				<span class="text-lg font-medium">{DASHBOARD_VIEWS.PROJECTS}</span>
			</Button>
		</div>
		{#if dashboardStore.currentView === DASHBOARD_VIEWS.PROJECTS}
			<PageDashboardProjects />
		{/if}
	</div>
{/if}

// src/app/dashboard/page.tsx
'use client';

import DashboardProjects from "@/components/dashboard/DashboardProjects";
import { Button } from "@/components/ui/button";
import { useDashboardStore } from "@/store/dashboardStore";
import { DASHBOARD_VIEWS } from "@/utils/contants/dashboardViews";
import { FolderKanban } from "lucide-react";


export default function DashboardPage() {
  const { currentView, setCurrentView } = useDashboardStore();

  function renderView() {
    switch (currentView) {
      case DASHBOARD_VIEWS.PROJECTS:
        return <DashboardProjects />;
      default:
        return <DashboardProjects />;
    }
  }

  return (
    <div className="flex h-full w-full gap-8">
      {/* Left Section - Projects List */}
      <div className="w-[20%] min-w-[250px]">
        <Button
          variant="ghost"
          className="text-white"
          onClick={() => setCurrentView(DASHBOARD_VIEWS.PROJECTS)}
        >
          <FolderKanban className="!h-5 !w-5" />
          <span className="text-lg font-medium">Projects</span>
        </Button>
      </div>
      {renderView()}
    </div>
  );
}
