// src/components/motion/PageTransition.tsx
"use client";

import { motion } from "framer-motion";
import { usePathname } from "next/navigation";

export function PageTransition({ children }: { children: React.ReactNode }) {
  const pathname = usePathname();

  return (
    <motion.div
      key={pathname}
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      transition={{ duration: 0.3, ease: "easeInOut" }}
      className="flex flex-1"
    >
      {children}
    </motion.div>
  );
}

// src/lib/components/PageTransition.svelte
<script lang="ts">
	import { fade } from 'svelte/transition';

	const { pathname, children } = $props();
	// Use the full pathname as the key for the transition
</script>

{#key pathname}
	<div
		in:fade={{ duration: 150, delay: 0 }}
    class="flex flex-1 items-center"
	>
		{@render children()}
	</div>
{/key}
